### ISSUE TITLE
3D Distance Calculation giving incorrect values.

### ISSUE THREAD

**Issue by junglehornet** [JungleHornet/distance-calc#5]
I haven’t had a chance to test if this is [https://github.com/JungleHornet/junglemath](junglemath’s) fault, so this would be a good first issue to test junglemath and find the issue. Any help appreciated.

**Comment by ghost** [comment]
I don't have any experience in Go but I can say this. Make sure the calc is doing this:
- for 2D: https://www.desmos.com/calculator/li9cvepgau
- for 3D: https://www.desmos.com/3d/913028f9c6
Tip: Desmos is great for making mathematical functions and testing them in a pure-math environment. They have 2D and 3D

**Comment by ghost** [comment]
The calc should look like this:

term1 = (x2 - x1)
term1 = term1 * term1

term2 = (y2 - y1)
term2 = term2 * term2

term3 = (z2 - z1)
term3 = term3 * term3

out = sqrt( term1 + term2 + term3 )

(If you do the 2D calc then ignore term3)

**Comment by junglehornet** [comment]
Thanks! I've done some testing and I now know that junglemath is correct, so it must be something with JungleCalculator. I will post updates here as I go.

**Comment by junglehornet** [comment]
I've found the culprit, I mistyped a lot of variable names (like 5-6 or smth I think), probably the result of copy paste but it should be all fixed now.
